### ISSUE TITLE
Save personal tricks - Creation page

### ISSUE THREAD

**Issue by bastislack** [bastislack/highline-freestyle#296]

**Comment by JulianDietzel** [comment]
The page for creating new custom tricks now exists with almost all input fields being functional. The implementation can be seen in #323 and was done by @WaldemarLehner for the absolute largest part.

This issue will be keep open though because three features are still missing:
- [x] Allowing the user to specify prerequisites for a trick (see #354)
- [x] Allowing the user to specify whether the trick is a variation of another trick (see #355)
- [x] Allowing the user to add videos (links to videos and optionally a start and end time) to a video (see #356)

These missing features now need to be addressed in one or more followup PRs

**Comment by JulianDietzel** [comment]
All sub-issues implemented, therefore this issue is now fully implemented.
